### ISSUE TITLE
is missing a file

### ISSUE THREAD

**Issue by taniaminter** [voice4net/TSAPIClient#1]
is missing the file Events.cs in project TSAPIClient.

**Comment by voice4net** [comment]
Hi Tania,

I added the missing file. Sorry for the inconvenience. Let me know if you encounter any more issues as I would like for this project to be of use to people even though I'm no longer actively developing it. I know that when I needed to find a .NET TSAPI project a few years ago, nothing existed that would meet my needs, and I spent a great deal of time working on this.

Thanks,

Brad
